export const Actions = {
	USER_LOADED: "USER_LOADED",
	USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
	USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
	USER_LOGIN_ERROR: "USER_LOGIN_ERROR",
	USER_LOGIN_REDIRECT_REQUEST: "USER_LOGIN_REDIRECT_REQUEST",
}